# https://gist.github.com/guioconnor/66a04a2c4292b8dcba22808fbc7fd68e

# specify language
language: c++

compiler:
  - clang-5
  - clang-6
  - clang-7
  - gcc-6
  - gcc-7
  - gcc-8

os: linux

# configure which branches to run
branches:
  # whitelist
  only:
    - main

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install $TRAVIS_COMPILER
    - $TRAVIS_COMPILER --version

script:
  - $TRAVIS_COMPILER unit_tests.cc -o unit_tests -O3 -Wall -Wextra -Iinclude -std=c++17 -Wshadow && ./unit_tests