# https://gist.github.com/guioconnor/66a04a2c4292b8dcba22808fbc7fd68e

language: c++
os: linux
dist: bionic

# configure which branches to run
branches:
  # whitelist
  only:
    - main

# https://github.com/boostorg/hana/blob/master/.travis.yml
matrix:
  include:
    # Clang 7
    - env: COMPILER=clang++-7  CPP="c++17"
      addons: { apt: { packages: ["clang-7",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7"] } }

    # Clang 8
    - env: COMPILER=clang++-8  CPP="c++17"
      addons: &defaults { apt: { packages: ["clang-8",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-8"] } }

    # Clang 9
    - env: COMPILER=clang++-9  CPP="c++17"
      addons: &defaults { apt: { packages: ["clang-9",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic-9"] } }

    # Clang 10
    - env: COMPILER=clang++-10  CPP="c++17"   SAN="-fsanitize=address"
      addons: &defaults { apt: { packages: ["clang-10",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # Clang 11
    #- env: COMPILER=clang++-11  CPP="c++17"
    #  addons: &defaults { apt: { packages: ["clang-11",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # Clang 12
    #- env: COMPILER=clang++-12  CPP="c++17"
    #  addons: &defaults { apt: { packages: ["clang-12",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # GCC 7
    - env: COMPILER=g++-7  CPP="c++17"
      addons: { apt: { packages: ["g++-7",], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 8
    - env: COMPILER=g++-8  CPP="c++17"
      addons: { apt: { packages: ["g++-8",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 9
    - env: COMPILER=g++-9  CPP="c++17"
      addons: { apt: { packages: ["g++-9",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 10
    - env: COMPILER=g++-10  CPP="c++17"
      addons: { apt: { packages: ["g++-10",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 11
    - env: COMPILER=g++-11  CPP="c++17"  SAN="-fsanitize=undefined,address,leak -fno-omit-frame-pointer"
      addons: { apt: { packages: ["g++-11",], sources: ["ubuntu-toolchain-r-test"] } }
      

    # Other c++ versions
    - env: COMPILER=clang++-10  CPP="c++14"
      addons: &defaults { apt: { packages: ["clang-10",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }
      
    - env: COMPILER=clang++-10  CPP="c++2a"
      addons: &defaults { apt: { packages: ["clang-10",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    - env: COMPILER=g++-11  CPP="c++14"
      addons: { apt: { packages: ["g++-11",], sources: ["ubuntu-toolchain-r-test"] } }

    - env: COMPILER=g++-11  CPP="c++2a"
      addons: { apt: { packages: ["g++-11",], sources: ["ubuntu-toolchain-r-test"] } }

before_install:
    - sudo apt-get update -qq
    - eval "${MATRIX_EVAL}"
    #- sudo apt-get install $TRAVIS_COMPILER
    #- $TRAVIS_COMPILER --version

install:
- if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
- ${CXX} --version

script:
  - $CXX unit_tests.cc -o unit_tests -O3 -Wall -Wextra -pedantic -Werror -Iinclude -std="$CPP" -Wshadow -D_GLIBCXX_DEBUG $SAN && ./unit_tests
