# https://gist.github.com/guioconnor/66a04a2c4292b8dcba22808fbc7fd68e

# specify language
language: c++

#compiler:
#  - clang
#  - clang-6
#  - clang-7
#  - gcc-6
#  - gcc-7
#  - gcc-8

os: linux
dist: bionic

# configure which branches to run
branches:
  # whitelist
  only:
    - main

# https://github.com/boostorg/hana/blob/master/.travis.yml
matrix:
  include:
    ##########################################################################
    # Build with the main configuration on all the supported compilers
    #
    # Note that we only use the memory checker on the main configuration to
    # speed up Travis builds.
    ##########################################################################
    # Clang 7
    - env: COMPILER=clang++-7
      addons: { apt: { packages: ["clang-7",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7"] } }

    # Clang 8
    - env: COMPILER=clang++-8
      addons: &defaults { apt: { packages: ["clang-8",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-8"] } }

    # Clang 9
    - env: COMPILER=clang++-9
      addons: &defaults { apt: { packages: ["clang-9",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic-9"] } }

    # Clang 10
    - env: COMPILER=clang++-10
      addons: &defaults { apt: { packages: ["clang-10",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # Clang 11
    - env: COMPILER=clang++-11
      addons: &defaults { apt: { packages: ["clang-11",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # Clang 12
    - env: COMPILER=clang++-12
      addons: &defaults { apt: { packages: ["clang-12",], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-bionic"] } }

    # GCC 7
    - env: COMPILER=g++-7
      addons: { apt: { packages: ["g++-7",], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 8
    - env: COMPILER=g++-8
      addons: { apt: { packages: ["g++-8",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 9
    - env: COMPILER=g++-9
      addons: { apt: { packages: ["g++-9",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 10
    - env: COMPILER=g++-10
      addons: { apt: { packages: ["g++-10",], sources: ["ubuntu-toolchain-r-test"] } }
      
    # GCC 11
    - env: COMPILER=g++-11
      addons: { apt: { packages: ["g++-11",], sources: ["ubuntu-toolchain-r-test"] } }
      



before_install:
    - sudo apt-get update -qq
    - eval "${MATRIX_EVAL}"
    #- sudo apt-get install $TRAVIS_COMPILER
    #- $TRAVIS_COMPILER --version

install:
- if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
- ${CXX} --version

script:
  - $CXX unit_tests.cc -o unit_tests -O3 -Wall -Wextra -Iinclude -std=c++17 -Wshadow && ./unit_tests
